#server.port=8080
#spring.datasource.url=jdbc:mysql://localhost:3306/car_management
#spring.datasource.username=root
#spring.datasource.password=
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#
#project.images=images/

server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_management?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true

